### ISSUE TITLE
get rid of the advertising

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#28]
will gold status fix this?

**Comment by monkeypants** [comment]
http://docs.readthedocs.org/en/latest/sponsors.html#sponsorship-information

    This promotion is not displayed for users with gold status, 
    or users that have donated in the past.

**Comment by markmuir87** [comment]
If we're going to suggest 'readthedocs' as one of the preferred documentation formats, it makes a lot of sense to sponsor. If we go down this path, we should look to sponsor under the auspices of the 'Australian Government', so that all departments and agencies can publish ad-free documentation. This would be consistent with the DTO's mandate to provide whole-of-government 'base infrastructure'.
