### ISSUE TITLE
Need to emphasise 'simplicity' as a key design principle

### ISSUE THREAD

**Issue by markmuir87** [AusDTO/apiguide#32]
I think we should strongly emphasise simplicity as a paramount design principle. This seems to be where we (the government) have gone horribly wrong in the past (e.g. SBR).

I'll add an extra paragraph to the 'developer empathy' section, which also explains _why_ simplicity is important from a public policy perspective (or, put another way, why we want to ensure as many developers as possible use our APIs).

Interestingly, it's the same reason google and others want you to use their APIs/platform: if developers build complementary products for your ecosystem, the value of your ecosystem increases. In the government's case, our 'ecosystem' is the economy in general.

**Comment by monkeypants** [comment]
I agree, but don't know how we could proscribe "simplicity" without being unhelpful.

Simplicity is a quality of well designed interfaces, but stating "design as simply as possible, but don't oversimplify" is really unhelpful advice. How do we expect someone to unambiguously self-assess the simplicity of their own interfaces?

How do we reduce the issue of simplicity to MUST and SHOULD conformance criteria that a developer could assess their product against?

**Comment by chris-beer** [comment]
Proscribed simplicty... love it.

"How do we expect someone to unambiguously self-assess the simplicity of their own interfaces?"

We (Aus Gov) already does this in mandating WCAG compliance. AND we expect assessment and reporting on compliance - self assessment or otherwise. e.g.

"1.4 Distinguishable: Make it easier for users to see and hear content...

3.1 Readable: Make text content readable and *understandable*.

3.2 Predictable: Make Web pages appear and operate in predictable ways.

Principle 3: Understandable - Information and the operation of user interface must be understandable."

In fact, having just popped open WCAG 2 to copy and paste - there is a lot of basic design thinking in there that not only openly infers simplicity is key (there is obvious REST principles in play throughout), but that could easily be applied to API / digital service design with only a little rewording. Not withstanding that any government API (i.e. web) must by definition meet WCAG from documentation through to Developer UI's (including headless IA patterns at the command line).
