### ISSUE TITLE
principles/granularity.rst: question about optimum granularity?

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#39]
I have a nagging doubt about this statement:

> APIs should be designed at the lowest practical level of granularity because this makes each service simpler and allows them to be combined in ways that suit the consumer.

I think it maybe more accurate to say "finest level of granularity that is cohesive and coherent".

Why split this particular hair? if you start with a 1:1 mapping of the paper form (for example), i.e. clearly to coarse, and then start breaking it down into sensible chunks that make sense in a wider context, the cohesion and coherence of those chunks is better than the original 1:1 mapping.  Great, you're winning... But if you take it to far, past the point of maximum cohesiveness, then not only do you start becoming less coherent, you also make a bad compromise with "distributed computing issues"; network reliability/latency/bandwidth issues, security/topology/administrative issues.

There's clearly a sweet spot, but it's not easy to define. Comments/suggestion/arguments welcome...

**Comment by onthebreeze** [comment]
I think the key is to identify the discrete business entities (resources) involved in the service.  The CRUD actions on the resource are the correct granularity.  For example in the gst lodgement form that includes business address information there are two entities - the address and the GSt obligation. 

If you can find different entities on your paper form that have a different lifecycle (eg in the real world there is no correlation between changing my address and doing a tax return) then you need to break down further 

Steve Capell
Mob: 0410 437854

**Comment by chris-beer** [comment]
(Views my own etc.)

I've been mulling over both of your statements for a few days.

a) Personally I prefer the term "practical" over "cohesive and coherent" as it infers simplicity (KISS).

b) In terms of the "hair splitting" - I agree with SC that the CRUD actions (or rather, the basic HTTP methods - GET, POST/PUT etc) are the correct granularity. But not that it necessarily relates to the discrete business entities as opposed to say, the basic function - GET is GET, POST is POST, (CRUD is CRUD) regardless of the entities involved. From an enterprise perspective, standardising the API function becomes key in terms of cost benefit - you may have different endpoints (a.k.a discrete business entities) internally in terms of where transaction flows end up, but at the end of the end of the day, you've "coded once and reused many" in terms of getting the data/input from A to B.

The sweet spot would seem to be that IF you can identify a common function across transactions (lodging a change of business address information for instance) - consider simply reviewing and aligning the lifecycles of the particular function rather than breaking things down further to find the lowest common denominator.

Incidentally I see a lot of similiarity in ontology/taxonomy/classification type metadata standard development (or even traditional DB modelling/normalisation) and API granularity in terms of getting to the sweet spot. Prehaps experience and learnings from those domains could help here?

(Oh - re: "eg in the real world there is no correlation between changing my address and doing a tax return" - Depends on how you look at it.  An address "change event" from a provenance point of view would include the intial address creation (where the change event is "nothing" to "something"). And you have to have an address in order to do a tax return/ complete the GST obligation. So there could be seen to be an inferred correlation there. This would be a perfect case in point - is it better to have seperate API's for "create address" and "change address"? Or just an "address" API that handles all CRUD methods based on role etc, regardless of the entity/system which receives the transactional data.)

**Comment by monkeypants** [comment]
There are a number of anti-patterns we want to avoid, for example:

 * building APIs with a 1:1 correspondence to paper forms (to coarse: not reusable, don't make me repeat myself)
 * pushing a low-level object protocol into the API layer (for fine: overcomplicate the distributed computing thing) 

The outcome we want is "well designed APIs", but it's difficult to specify that as a conformance criteria. "Well designed" is a subjective badge of excellence, not much more being useful and usable. It's easier to recognise than specify.

The old adage "you have to know the rules before you can break them" probably applies. If designers generally used HTTP verbs for CRUD on endpoints that represent the classed in their domain model, and then they are have a good reason to deviate from that pattern they are probably right to do so.

I agree with your link to ontological modelling. It would be great if designers generally linked the semantics of local interfaces with canonical ones (interface reification). I think that sort of on the horizon, but we would need more examples in the wild before we encouraged it.

**Comment by chris-beer** [comment]
"It's easier to recognise than specify" - true that.

If the outcome is "well designed API's" rather than "cost-effective (to agencies) enterprise wide API's" - prehaps therein lies the key - one could get Dev's to rate API's in the API register - it will soon become apparent what "optimum granularity" is in terms of both internal and external DX.
